// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TextCheckIn.Data.Context;

#nullable disable

namespace TextCheckIn.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030200731_InitialSQLServerMigration")]
    partial class InitialSQLServerMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TextCheckIn.Data.Entities.CheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientLocationId")
                        .HasColumnType("int")
                        .HasColumnName("client_location_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("datetime");

                    b.Property<int?>("EstimatedMileage")
                        .HasColumnType("int")
                        .HasColumnName("estimated_mileage");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit")
                        .HasColumnName("is_processed");

                    b.Property<Guid?>("OmnixLocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("omnix_location_id");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int")
                        .HasColumnName("store_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uuid");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StoreId");

                    b.HasIndex("VehicleId");

                    b.ToTable("check_ins", (string)null);
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.CheckInService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckInId")
                        .HasColumnType("int")
                        .HasColumnName("check_in_id");

                    b.Property<int>("IntervalMiles")
                        .HasColumnType("int")
                        .HasColumnName("interval_miles");

                    b.Property<bool>("IsCustomerSelected")
                        .HasColumnType("bit")
                        .HasColumnName("is_customer_selected");

                    b.Property<int?>("LastServiceMiles")
                        .HasColumnType("int")
                        .HasColumnName("last_service_miles");

                    b.Property<int>("MileageBucket")
                        .HasColumnType("int")
                        .HasColumnName("mileage_bucket");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("service_id");

                    b.HasKey("Id");

                    b.HasIndex("CheckInId");

                    b.HasIndex("ServiceId");

                    b.ToTable("check_in_services", (string)null);
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.CheckInSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_activity");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("check_in_sessions", (string)null);
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("customer_created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("customer_email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("customer_first_name");

                    b.Property<bool>("IsFleetCustomer")
                        .HasColumnType("bit")
                        .HasColumnName("is_fleet_customer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("customer_last_name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("customer_phone_number");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("customer_updated_at");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_uuid");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.CustomersVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("customer_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("customers_vehicles", (string)null);
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<Guid>("ServiceUuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("service_uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("services", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete transmission fluid replacement and system inspection to ensure smooth shifting and optimal performance.",
                            EstimatedDurationMinutes = 45,
                            Name = "Transmission service",
                            Price = 189.99m,
                            ServiceUuid = new Guid("c6f1ef6a-8d9f-46ac-94e8-359c3aa11ffd"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Coolant system flush and replacement to prevent overheating and maintain optimal engine temperature.",
                            EstimatedDurationMinutes = 30,
                            Name = "Coolant service",
                            Price = 149.99m,
                            ServiceUuid = new Guid("3e354208-59d0-46e5-a6a0-f3cb47938c44"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deep cleaning of intake valves and combustion chambers to restore engine performance and fuel efficiency.",
                            EstimatedDurationMinutes = 60,
                            Name = "Intake system cleaning",
                            Price = 229.99m,
                            ServiceUuid = new Guid("4d816599-6a13-4aa4-959a-c8eb8168e71c"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Power steering fluid replacement to ensure easy steering and prevent system damage.",
                            EstimatedDurationMinutes = 20,
                            Name = "Power steering fluid service",
                            Price = 89.99m,
                            ServiceUuid = new Guid("672b3a26-3f03-4db7-a7fb-317f4f60baf2"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gearbox fluid replacement and inspection to maintain smooth gear changes and extend transmission life.",
                            EstimatedDurationMinutes = 40,
                            Name = "Gear box service",
                            Price = 169.99m,
                            ServiceUuid = new Guid("b54ad209-7e30-47c7-828d-1174dcebbf63"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cabin air filter replacement to ensure clean air circulation and optimal HVAC performance.",
                            EstimatedDurationMinutes = 15,
                            Name = "Cabin Air Filter",
                            Price = 49.99m,
                            ServiceUuid = new Guid("f072fcb0-425f-4961-9894-cb6b7aec5133"),
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.StateCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("state_codes", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "AL",
                            Name = "Alabama"
                        },
                        new
                        {
                            Code = "AK",
                            Name = "Alaska"
                        },
                        new
                        {
                            Code = "AZ",
                            Name = "Arizona"
                        },
                        new
                        {
                            Code = "AR",
                            Name = "Arkansas"
                        },
                        new
                        {
                            Code = "CA",
                            Name = "California"
                        },
                        new
                        {
                            Code = "CO",
                            Name = "Colorado"
                        },
                        new
                        {
                            Code = "CT",
                            Name = "Connecticut"
                        },
                        new
                        {
                            Code = "DE",
                            Name = "Delaware"
                        },
                        new
                        {
                            Code = "FL",
                            Name = "Florida"
                        },
                        new
                        {
                            Code = "GA",
                            Name = "Georgia"
                        },
                        new
                        {
                            Code = "HI",
                            Name = "Hawaii"
                        },
                        new
                        {
                            Code = "ID",
                            Name = "Idaho"
                        },
                        new
                        {
                            Code = "IL",
                            Name = "Illinois"
                        },
                        new
                        {
                            Code = "IN",
                            Name = "Indiana"
                        },
                        new
                        {
                            Code = "IA",
                            Name = "Iowa"
                        },
                        new
                        {
                            Code = "KS",
                            Name = "Kansas"
                        },
                        new
                        {
                            Code = "KY",
                            Name = "Kentucky"
                        },
                        new
                        {
                            Code = "LA",
                            Name = "Louisiana"
                        },
                        new
                        {
                            Code = "ME",
                            Name = "Maine"
                        },
                        new
                        {
                            Code = "MD",
                            Name = "Maryland"
                        },
                        new
                        {
                            Code = "MA",
                            Name = "Massachusetts"
                        },
                        new
                        {
                            Code = "MI",
                            Name = "Michigan"
                        },
                        new
                        {
                            Code = "MN",
                            Name = "Minnesota"
                        },
                        new
                        {
                            Code = "MS",
                            Name = "Mississippi"
                        },
                        new
                        {
                            Code = "MO",
                            Name = "Missouri"
                        },
                        new
                        {
                            Code = "MT",
                            Name = "Montana"
                        },
                        new
                        {
                            Code = "NE",
                            Name = "Nebraska"
                        },
                        new
                        {
                            Code = "NV",
                            Name = "Nevada"
                        },
                        new
                        {
                            Code = "NH",
                            Name = "New Hampshire"
                        },
                        new
                        {
                            Code = "NJ",
                            Name = "New Jersey"
                        },
                        new
                        {
                            Code = "NM",
                            Name = "New Mexico"
                        },
                        new
                        {
                            Code = "NY",
                            Name = "New York"
                        },
                        new
                        {
                            Code = "NC",
                            Name = "North Carolina"
                        },
                        new
                        {
                            Code = "ND",
                            Name = "North Dakota"
                        },
                        new
                        {
                            Code = "OH",
                            Name = "Ohio"
                        },
                        new
                        {
                            Code = "OK",
                            Name = "Oklahoma"
                        },
                        new
                        {
                            Code = "OR",
                            Name = "Oregon"
                        },
                        new
                        {
                            Code = "PA",
                            Name = "Pennsylvania"
                        },
                        new
                        {
                            Code = "RI",
                            Name = "Rhode Island"
                        },
                        new
                        {
                            Code = "SC",
                            Name = "South Carolina"
                        },
                        new
                        {
                            Code = "SD",
                            Name = "South Dakota"
                        },
                        new
                        {
                            Code = "TN",
                            Name = "Tennessee"
                        },
                        new
                        {
                            Code = "TX",
                            Name = "Texas"
                        },
                        new
                        {
                            Code = "UT",
                            Name = "Utah"
                        },
                        new
                        {
                            Code = "VT",
                            Name = "Vermont"
                        },
                        new
                        {
                            Code = "VA",
                            Name = "Virginia"
                        },
                        new
                        {
                            Code = "WA",
                            Name = "Washington"
                        },
                        new
                        {
                            Code = "WV",
                            Name = "West Virginia"
                        },
                        new
                        {
                            Code = "WI",
                            Name = "Wisconsin"
                        },
                        new
                        {
                            Code = "WY",
                            Name = "Wyoming"
                        },
                        new
                        {
                            Code = "DC",
                            Name = "District of Columbia"
                        });
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("StateCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("state_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uuid");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id");

                    b.HasIndex("StateCode");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("LastMileage")
                        .HasColumnType("int")
                        .HasColumnName("last_mileage");

                    b.Property<DateTime?>("LastServiceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_service_date");

                    b.Property<int?>("LastServiceMileage")
                        .HasColumnType("int")
                        .HasColumnName("last_service_mileage");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("license_plate");

                    b.Property<string>("Make")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("model");

                    b.Property<string>("StateCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("state_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleUUID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vehicle_uuid");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasColumnName("vin");

                    b.Property<int?>("YearOfMake")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("year_of_make");

                    b.HasKey("Id");

                    b.HasIndex("StateCode");

                    b.HasIndex("Vin")
                        .IsUnique()
                        .HasFilter("[vin] IS NOT NULL");

                    b.HasIndex("LicensePlate", "StateCode")
                        .IsUnique()
                        .HasFilter("[state_code] IS NOT NULL");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.CheckIn", b =>
                {
                    b.HasOne("TextCheckIn.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TextCheckIn.Data.Entities.Store", "Store")
                        .WithMany("CheckIns")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TextCheckIn.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("CheckIns")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Store");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.CheckInService", b =>
                {
                    b.HasOne("TextCheckIn.Data.Entities.CheckIn", "CheckIn")
                        .WithMany("CheckInServices")
                        .HasForeignKey("CheckInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TextCheckIn.Data.Entities.Service", "Service")
                        .WithMany("CheckInServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckIn");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.CheckInSession", b =>
                {
                    b.HasOne("TextCheckIn.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.CustomersVehicle", b =>
                {
                    b.HasOne("TextCheckIn.Data.Entities.Customer", "Customer")
                        .WithMany("CustomersVehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TextCheckIn.Data.Entities.Vehicle", "Vehicle")
                        .WithMany("CustomersVehicles")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.Store", b =>
                {
                    b.HasOne("TextCheckIn.Data.Entities.StateCode", "State")
                        .WithMany("Stores")
                        .HasForeignKey("StateCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("State");
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.Vehicle", b =>
                {
                    b.HasOne("TextCheckIn.Data.Entities.StateCode", "State")
                        .WithMany("Vehicles")
                        .HasForeignKey("StateCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("State");
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.CheckIn", b =>
                {
                    b.Navigation("CheckInServices");
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.Customer", b =>
                {
                    b.Navigation("CustomersVehicles");
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.Service", b =>
                {
                    b.Navigation("CheckInServices");
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.StateCode", b =>
                {
                    b.Navigation("Stores");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.Store", b =>
                {
                    b.Navigation("CheckIns");
                });

            modelBuilder.Entity("TextCheckIn.Data.Entities.Vehicle", b =>
                {
                    b.Navigation("CheckIns");

                    b.Navigation("CustomersVehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
